name: raft-based-kv

services:
  raft-1:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.node
    ports:
      - 50051:50051
    environment:
        node_name: A
        role: leader
        election_time: 5
        followers: raft-node-2,raft-node-3,raft-node-4,raft-node-5
    container_name: raft-node-1

  raft-2:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.node
    environment:
        node_name: B
        role: follower
    container_name: raft-node-2
  raft-3:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.node
    environment:
        node_name: C 
        role: follower
    container_name: raft-node-3
  raft-4:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.node
    environment:
        node_name: D
        role: follower
    container_name: raft-node-4
  raft-5:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.node
    container_name: raft-node-5
    environment:
        node_name: E
        role: follower
#   raft-aware-proxy:
#
# volumes:
# networks:
#
