FROM golang:1.26.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o raft-proxy ./cmd/raft-aware-proxy

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/raft-proxy .

CMD ["./raft-proxy"]
