// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/heartbeat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=NodeName,proto3" json:"NodeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderDetails) Reset() {
	*x = LeaderDetails{}
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderDetails) ProtoMessage() {}

func (x *LeaderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderDetails.ProtoReflect.Descriptor instead.
func (*LeaderDetails) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderDetails) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type ClientConfirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfirmation) Reset() {
	*x = ClientConfirmation{}
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfirmation) ProtoMessage() {}

func (x *ClientConfirmation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_heartbeat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfirmation.ProtoReflect.Descriptor instead.
func (*ClientConfirmation) Descriptor() ([]byte, []int) {
	return file_proto_heartbeat_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfirmation) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_proto_heartbeat_proto protoreflect.FileDescriptor

const file_proto_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x15proto/heartbeat.proto\"+\n" +
	"\rLeaderDetails\x12\x1a\n" +
	"\bNodeName\x18\x01 \x01(\tR\bNodeName\"(\n" +
	"\x12ClientConfirmation\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term2H\n" +
	"\rSendHeartbeat\x127\n" +
	"\x10RecieveHeartbeat\x12\x0e.LeaderDetails\x1a\x13.ClientConfirmationB\tZ\a./protob\x06proto3"

var (
	file_proto_heartbeat_proto_rawDescOnce sync.Once
	file_proto_heartbeat_proto_rawDescData []byte
)

func file_proto_heartbeat_proto_rawDescGZIP() []byte {
	file_proto_heartbeat_proto_rawDescOnce.Do(func() {
		file_proto_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)))
	})
	return file_proto_heartbeat_proto_rawDescData
}

var file_proto_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_heartbeat_proto_goTypes = []any{
	(*LeaderDetails)(nil),      // 0: LeaderDetails
	(*ClientConfirmation)(nil), // 1: ClientConfirmation
}
var file_proto_heartbeat_proto_depIdxs = []int32{
	0, // 0: SendHeartbeat.RecieveHeartbeat:input_type -> LeaderDetails
	1, // 1: SendHeartbeat.RecieveHeartbeat:output_type -> ClientConfirmation
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_heartbeat_proto_init() }
func file_proto_heartbeat_proto_init() {
	if File_proto_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_heartbeat_proto_rawDesc), len(file_proto_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_heartbeat_proto_goTypes,
		DependencyIndexes: file_proto_heartbeat_proto_depIdxs,
		MessageInfos:      file_proto_heartbeat_proto_msgTypes,
	}.Build()
	File_proto_heartbeat_proto = out.File
	file_proto_heartbeat_proto_goTypes = nil
	file_proto_heartbeat_proto_depIdxs = nil
}
