// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/heartbeat.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SendHeartbeat_RecieveHeartbeat_FullMethodName = "/SendHeartbeat/RecieveHeartbeat"
)

// SendHeartbeatClient is the client API for SendHeartbeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SendHeartbeatClient interface {
	RecieveHeartbeat(ctx context.Context, in *LeaderDetails, opts ...grpc.CallOption) (*ClientConfirmation, error)
}

type sendHeartbeatClient struct {
	cc grpc.ClientConnInterface
}

func NewSendHeartbeatClient(cc grpc.ClientConnInterface) SendHeartbeatClient {
	return &sendHeartbeatClient{cc}
}

func (c *sendHeartbeatClient) RecieveHeartbeat(ctx context.Context, in *LeaderDetails, opts ...grpc.CallOption) (*ClientConfirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientConfirmation)
	err := c.cc.Invoke(ctx, SendHeartbeat_RecieveHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendHeartbeatServer is the server API for SendHeartbeat service.
// All implementations must embed UnimplementedSendHeartbeatServer
// for forward compatibility.
type SendHeartbeatServer interface {
	RecieveHeartbeat(context.Context, *LeaderDetails) (*ClientConfirmation, error)
	mustEmbedUnimplementedSendHeartbeatServer()
}

// UnimplementedSendHeartbeatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSendHeartbeatServer struct{}

func (UnimplementedSendHeartbeatServer) RecieveHeartbeat(context.Context, *LeaderDetails) (*ClientConfirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method RecieveHeartbeat not implemented")
}
func (UnimplementedSendHeartbeatServer) mustEmbedUnimplementedSendHeartbeatServer() {}
func (UnimplementedSendHeartbeatServer) testEmbeddedByValue()                       {}

// UnsafeSendHeartbeatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SendHeartbeatServer will
// result in compilation errors.
type UnsafeSendHeartbeatServer interface {
	mustEmbedUnimplementedSendHeartbeatServer()
}

func RegisterSendHeartbeatServer(s grpc.ServiceRegistrar, srv SendHeartbeatServer) {
	// If the following call panics, it indicates UnimplementedSendHeartbeatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SendHeartbeat_ServiceDesc, srv)
}

func _SendHeartbeat_RecieveHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendHeartbeatServer).RecieveHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SendHeartbeat_RecieveHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendHeartbeatServer).RecieveHeartbeat(ctx, req.(*LeaderDetails))
	}
	return interceptor(ctx, in, info, handler)
}

// SendHeartbeat_ServiceDesc is the grpc.ServiceDesc for SendHeartbeat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SendHeartbeat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SendHeartbeat",
	HandlerType: (*SendHeartbeatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecieveHeartbeat",
			Handler:    _SendHeartbeat_RecieveHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/heartbeat.proto",
}
