// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leader        string                 `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderDetails) Reset() {
	*x = LeaderDetails{}
	mi := &file_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderDetails) ProtoMessage() {}

func (x *LeaderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderDetails.ProtoReflect.Descriptor instead.
func (*LeaderDetails) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *LeaderDetails) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

type NodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*NodeResponse_LeaderDetails
	//	*NodeResponse_ClientResponse
	Result        isNodeResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeResponse) Reset() {
	*x = NodeResponse{}
	mi := &file_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeResponse) ProtoMessage() {}

func (x *NodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeResponse.ProtoReflect.Descriptor instead.
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *NodeResponse) GetResult() isNodeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *NodeResponse) GetLeaderDetails() *LeaderDetails {
	if x != nil {
		if x, ok := x.Result.(*NodeResponse_LeaderDetails); ok {
			return x.LeaderDetails
		}
	}
	return nil
}

func (x *NodeResponse) GetClientResponse() *ClientResponse {
	if x != nil {
		if x, ok := x.Result.(*NodeResponse_ClientResponse); ok {
			return x.ClientResponse
		}
	}
	return nil
}

type isNodeResponse_Result interface {
	isNodeResponse_Result()
}

type NodeResponse_LeaderDetails struct {
	LeaderDetails *LeaderDetails `protobuf:"bytes,1,opt,name=leaderDetails,proto3,oneof"`
}

type NodeResponse_ClientResponse struct {
	ClientResponse *ClientResponse `protobuf:"bytes,2,opt,name=clientResponse,proto3,oneof"`
}

func (*NodeResponse_LeaderDetails) isNodeResponse_Result() {}

func (*NodeResponse_ClientResponse) isNodeResponse_Result() {}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  int32                  `protobuf:"varint,1,opt,name=responseCode,proto3" json:"responseCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_proto_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{2}
}

func (x *ClientResponse) GetResponseCode() int32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

type KeyValuePair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePair) Reset() {
	*x = KeyValuePair{}
	mi := &file_proto_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePair) ProtoMessage() {}

func (x *KeyValuePair) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePair.ProtoReflect.Descriptor instead.
func (*KeyValuePair) Descriptor() ([]byte, []int) {
	return file_proto_proto_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValuePair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_proto_proto protoreflect.FileDescriptor

const file_proto_proto_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proto.proto\"'\n" +
	"\rLeaderDetails\x12\x16\n" +
	"\x06leader\x18\x01 \x01(\tR\x06leader\"\x8b\x01\n" +
	"\fNodeResponse\x126\n" +
	"\rleaderDetails\x18\x01 \x01(\v2\x0e.LeaderDetailsH\x00R\rleaderDetails\x129\n" +
	"\x0eclientResponse\x18\x02 \x01(\v2\x0f.ClientResponseH\x00R\x0eclientResponseB\b\n" +
	"\x06result\"4\n" +
	"\x0eClientResponse\x12\"\n" +
	"\fresponseCode\x18\x01 \x01(\x05R\fresponseCode\"6\n" +
	"\fKeyValuePair\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value2@\n" +
	"\x11KeyValueOperation\x12+\n" +
	"\vAddKeyValue\x12\r.KeyValuePair\x1a\r.NodeResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_proto_proto_rawDescOnce sync.Once
	file_proto_proto_proto_rawDescData []byte
)

func file_proto_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)))
	})
	return file_proto_proto_proto_rawDescData
}

var file_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_proto_proto_goTypes = []any{
	(*LeaderDetails)(nil),  // 0: LeaderDetails
	(*NodeResponse)(nil),   // 1: NodeResponse
	(*ClientResponse)(nil), // 2: ClientResponse
	(*KeyValuePair)(nil),   // 3: KeyValuePair
}
var file_proto_proto_proto_depIdxs = []int32{
	0, // 0: NodeResponse.leaderDetails:type_name -> LeaderDetails
	2, // 1: NodeResponse.clientResponse:type_name -> ClientResponse
	3, // 2: KeyValueOperation.AddKeyValue:input_type -> KeyValuePair
	1, // 3: KeyValueOperation.AddKeyValue:output_type -> NodeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proto_proto_init() }
func file_proto_proto_proto_init() {
	if File_proto_proto_proto != nil {
		return
	}
	file_proto_proto_proto_msgTypes[1].OneofWrappers = []any{
		(*NodeResponse_LeaderDetails)(nil),
		(*NodeResponse_ClientResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_proto_rawDesc), len(file_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_proto_msgTypes,
	}.Build()
	File_proto_proto_proto = out.File
	file_proto_proto_proto_goTypes = nil
	file_proto_proto_proto_depIdxs = nil
}
