// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyValueOperation_AddKeyValue_FullMethodName = "/KeyValueOperation/AddKeyValue"
)

// KeyValueOperationClient is the client API for KeyValueOperation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueOperationClient interface {
	AddKeyValue(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*NodeResponse, error)
}

type keyValueOperationClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueOperationClient(cc grpc.ClientConnInterface) KeyValueOperationClient {
	return &keyValueOperationClient{cc}
}

func (c *keyValueOperationClient) AddKeyValue(ctx context.Context, in *KeyValuePair, opts ...grpc.CallOption) (*NodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResponse)
	err := c.cc.Invoke(ctx, KeyValueOperation_AddKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyValueOperationServer is the server API for KeyValueOperation service.
// All implementations must embed UnimplementedKeyValueOperationServer
// for forward compatibility.
type KeyValueOperationServer interface {
	AddKeyValue(context.Context, *KeyValuePair) (*NodeResponse, error)
	mustEmbedUnimplementedKeyValueOperationServer()
}

// UnimplementedKeyValueOperationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyValueOperationServer struct{}

func (UnimplementedKeyValueOperationServer) AddKeyValue(context.Context, *KeyValuePair) (*NodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddKeyValue not implemented")
}
func (UnimplementedKeyValueOperationServer) mustEmbedUnimplementedKeyValueOperationServer() {}
func (UnimplementedKeyValueOperationServer) testEmbeddedByValue()                           {}

// UnsafeKeyValueOperationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueOperationServer will
// result in compilation errors.
type UnsafeKeyValueOperationServer interface {
	mustEmbedUnimplementedKeyValueOperationServer()
}

func RegisterKeyValueOperationServer(s grpc.ServiceRegistrar, srv KeyValueOperationServer) {
	// If the following call panics, it indicates UnimplementedKeyValueOperationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyValueOperation_ServiceDesc, srv)
}

func _KeyValueOperation_AddKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValuePair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueOperationServer).AddKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyValueOperation_AddKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueOperationServer).AddKeyValue(ctx, req.(*KeyValuePair))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyValueOperation_ServiceDesc is the grpc.ServiceDesc for KeyValueOperation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValueOperation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "KeyValueOperation",
	HandlerType: (*KeyValueOperationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddKeyValue",
			Handler:    _KeyValueOperation_AddKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
