// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/ProxyToNode.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_KeyValue
	//	*Response_LeaderDetails
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_ProxyToNode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyToNode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_ProxyToNode_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetKeyValue() *KeyValue {
	if x != nil {
		if x, ok := x.Result.(*Response_KeyValue); ok {
			return x.KeyValue
		}
	}
	return nil
}

func (x *Response) GetLeaderDetails() *LeaderDetails {
	if x != nil {
		if x, ok := x.Result.(*Response_LeaderDetails); ok {
			return x.LeaderDetails
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_KeyValue struct {
	KeyValue *KeyValue `protobuf:"bytes,1,opt,name=KeyValue,proto3,oneof"`
}

type Response_LeaderDetails struct {
	LeaderDetails *LeaderDetails `protobuf:"bytes,2,opt,name=LeaderDetails,proto3,oneof"`
}

func (*Response_KeyValue) isResponse_Result() {}

func (*Response_LeaderDetails) isResponse_Result() {}

type LeaderDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	LeaderName    string                 `protobuf:"bytes,2,opt,name=LeaderName,proto3" json:"LeaderName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderDetails) Reset() {
	*x = LeaderDetails{}
	mi := &file_proto_ProxyToNode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderDetails) ProtoMessage() {}

func (x *LeaderDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyToNode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderDetails.ProtoReflect.Descriptor instead.
func (*LeaderDetails) Descriptor() ([]byte, []int) {
	return file_proto_ProxyToNode_proto_rawDescGZIP(), []int{1}
}

func (x *LeaderDetails) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LeaderDetails) GetLeaderName() string {
	if x != nil {
		return x.LeaderName
	}
	return ""
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_proto_ProxyToNode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyToNode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_proto_ProxyToNode_proto_rawDescGZIP(), []int{2}
}

func (x *KeyValue) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_proto_ProxyToNode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ProxyToNode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_ProxyToNode_proto_rawDescGZIP(), []int{3}
}

func (x *Key) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Key) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_ProxyToNode_proto protoreflect.FileDescriptor

const file_proto_ProxyToNode_proto_rawDesc = "" +
	"\n" +
	"\x17proto/ProxyToNode.proto\"u\n" +
	"\bResponse\x12'\n" +
	"\bKeyValue\x18\x01 \x01(\v2\t.KeyValueH\x00R\bKeyValue\x126\n" +
	"\rLeaderDetails\x18\x02 \x01(\v2\x0e.LeaderDetailsH\x00R\rLeaderDetailsB\b\n" +
	"\x06result\"C\n" +
	"\rLeaderDetails\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x1e\n" +
	"\n" +
	"LeaderName\x18\x02 \x01(\tR\n" +
	"LeaderName\"F\n" +
	"\bKeyValue\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\"+\n" +
	"\x03Key\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x10\n" +
	"\x03Key\x18\x02 \x01(\tR\x03Key2\x9a\x01\n" +
	"\vProxyToNode\x12\x1e\n" +
	"\vGetKeyValue\x12\x04.Key\x1a\t.Response\x12#\n" +
	"\vAddKeyValue\x12\t.KeyValue\x1a\t.Response\x12!\n" +
	"\x0eDeleteKeyValue\x12\x04.Key\x1a\t.Response\x12#\n" +
	"\vPutKeyValue\x12\t.KeyValue\x1a\t.ResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_ProxyToNode_proto_rawDescOnce sync.Once
	file_proto_ProxyToNode_proto_rawDescData []byte
)

func file_proto_ProxyToNode_proto_rawDescGZIP() []byte {
	file_proto_ProxyToNode_proto_rawDescOnce.Do(func() {
		file_proto_ProxyToNode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ProxyToNode_proto_rawDesc), len(file_proto_ProxyToNode_proto_rawDesc)))
	})
	return file_proto_ProxyToNode_proto_rawDescData
}

var file_proto_ProxyToNode_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ProxyToNode_proto_goTypes = []any{
	(*Response)(nil),      // 0: Response
	(*LeaderDetails)(nil), // 1: LeaderDetails
	(*KeyValue)(nil),      // 2: KeyValue
	(*Key)(nil),           // 3: Key
}
var file_proto_ProxyToNode_proto_depIdxs = []int32{
	2, // 0: Response.KeyValue:type_name -> KeyValue
	1, // 1: Response.LeaderDetails:type_name -> LeaderDetails
	3, // 2: ProxyToNode.GetKeyValue:input_type -> Key
	2, // 3: ProxyToNode.AddKeyValue:input_type -> KeyValue
	3, // 4: ProxyToNode.DeleteKeyValue:input_type -> Key
	2, // 5: ProxyToNode.PutKeyValue:input_type -> KeyValue
	0, // 6: ProxyToNode.GetKeyValue:output_type -> Response
	0, // 7: ProxyToNode.AddKeyValue:output_type -> Response
	0, // 8: ProxyToNode.DeleteKeyValue:output_type -> Response
	0, // 9: ProxyToNode.PutKeyValue:output_type -> Response
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ProxyToNode_proto_init() }
func file_proto_ProxyToNode_proto_init() {
	if File_proto_ProxyToNode_proto != nil {
		return
	}
	file_proto_ProxyToNode_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_KeyValue)(nil),
		(*Response_LeaderDetails)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ProxyToNode_proto_rawDesc), len(file_proto_ProxyToNode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ProxyToNode_proto_goTypes,
		DependencyIndexes: file_proto_ProxyToNode_proto_depIdxs,
		MessageInfos:      file_proto_ProxyToNode_proto_msgTypes,
	}.Build()
	File_proto_ProxyToNode_proto = out.File
	file_proto_ProxyToNode_proto_goTypes = nil
	file_proto_ProxyToNode_proto_depIdxs = nil
}
