// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/ProxyToNode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyToNode_GetKeyValue_FullMethodName    = "/ProxyToNode/GetKeyValue"
	ProxyToNode_AddKeyValue_FullMethodName    = "/ProxyToNode/AddKeyValue"
	ProxyToNode_DeleteKeyValue_FullMethodName = "/ProxyToNode/DeleteKeyValue"
	ProxyToNode_PutKeyValue_FullMethodName    = "/ProxyToNode/PutKeyValue"
)

// ProxyToNodeClient is the client API for ProxyToNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProxyToNodeClient interface {
	GetKeyValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error)
	AddKeyValue(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error)
	DeleteKeyValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error)
	PutKeyValue(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error)
}

type proxyToNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyToNodeClient(cc grpc.ClientConnInterface) ProxyToNodeClient {
	return &proxyToNodeClient{cc}
}

func (c *proxyToNodeClient) GetKeyValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ProxyToNode_GetKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyToNodeClient) AddKeyValue(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ProxyToNode_AddKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyToNodeClient) DeleteKeyValue(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ProxyToNode_DeleteKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyToNodeClient) PutKeyValue(ctx context.Context, in *KeyValue, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, ProxyToNode_PutKeyValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyToNodeServer is the server API for ProxyToNode service.
// All implementations must embed UnimplementedProxyToNodeServer
// for forward compatibility.
type ProxyToNodeServer interface {
	GetKeyValue(context.Context, *Key) (*Response, error)
	AddKeyValue(context.Context, *KeyValue) (*Response, error)
	DeleteKeyValue(context.Context, *Key) (*Response, error)
	PutKeyValue(context.Context, *KeyValue) (*Response, error)
	mustEmbedUnimplementedProxyToNodeServer()
}

// UnimplementedProxyToNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyToNodeServer struct{}

func (UnimplementedProxyToNodeServer) GetKeyValue(context.Context, *Key) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyValue not implemented")
}
func (UnimplementedProxyToNodeServer) AddKeyValue(context.Context, *KeyValue) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddKeyValue not implemented")
}
func (UnimplementedProxyToNodeServer) DeleteKeyValue(context.Context, *Key) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKeyValue not implemented")
}
func (UnimplementedProxyToNodeServer) PutKeyValue(context.Context, *KeyValue) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PutKeyValue not implemented")
}
func (UnimplementedProxyToNodeServer) mustEmbedUnimplementedProxyToNodeServer() {}
func (UnimplementedProxyToNodeServer) testEmbeddedByValue()                     {}

// UnsafeProxyToNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyToNodeServer will
// result in compilation errors.
type UnsafeProxyToNodeServer interface {
	mustEmbedUnimplementedProxyToNodeServer()
}

func RegisterProxyToNodeServer(s grpc.ServiceRegistrar, srv ProxyToNodeServer) {
	// If the following call panics, it indicates UnimplementedProxyToNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyToNode_ServiceDesc, srv)
}

func _ProxyToNode_GetKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyToNodeServer).GetKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyToNode_GetKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyToNodeServer).GetKeyValue(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyToNode_AddKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyToNodeServer).AddKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyToNode_AddKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyToNodeServer).AddKeyValue(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyToNode_DeleteKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyToNodeServer).DeleteKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyToNode_DeleteKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyToNodeServer).DeleteKeyValue(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProxyToNode_PutKeyValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyToNodeServer).PutKeyValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyToNode_PutKeyValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyToNodeServer).PutKeyValue(ctx, req.(*KeyValue))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyToNode_ServiceDesc is the grpc.ServiceDesc for ProxyToNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyToNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ProxyToNode",
	HandlerType: (*ProxyToNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeyValue",
			Handler:    _ProxyToNode_GetKeyValue_Handler,
		},
		{
			MethodName: "AddKeyValue",
			Handler:    _ProxyToNode_AddKeyValue_Handler,
		},
		{
			MethodName: "DeleteKeyValue",
			Handler:    _ProxyToNode_DeleteKeyValue_Handler,
		},
		{
			MethodName: "PutKeyValue",
			Handler:    _ProxyToNode_PutKeyValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ProxyToNode.proto",
}
