// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/Voting.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vote          bool                   `protobuf:"varint,1,opt,name=vote,proto3" json:"vote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_proto_Voting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Voting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_proto_Voting_proto_rawDescGZIP(), []int{0}
}

func (x *Vote) GetVote() bool {
	if x != nil {
		return x.Vote
	}
	return false
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Log           int32                  `protobuf:"varint,2,opt,name=log,proto3" json:"log,omitempty"`
	NodeName      string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_Voting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_Voting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_Voting_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *NodeInfo) GetLog() int32 {
	if x != nil {
		return x.Log
	}
	return 0
}

func (x *NodeInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_proto_Voting_proto protoreflect.FileDescriptor

const file_proto_Voting_proto_rawDesc = "" +
	"\n" +
	"\x12proto/Voting.proto\"\x1a\n" +
	"\x04Vote\x12\x12\n" +
	"\x04vote\x18\x01 \x01(\bR\x04vote\"M\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12\x10\n" +
	"\x03log\x18\x02 \x01(\x05R\x03log\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName20\n" +
	"\rVotingService\x12\x1f\n" +
	"\vStartVoting\x12\t.NodeInfo\x1a\x05.VoteB\tZ\a./protob\x06proto3"

var (
	file_proto_Voting_proto_rawDescOnce sync.Once
	file_proto_Voting_proto_rawDescData []byte
)

func file_proto_Voting_proto_rawDescGZIP() []byte {
	file_proto_Voting_proto_rawDescOnce.Do(func() {
		file_proto_Voting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_Voting_proto_rawDesc), len(file_proto_Voting_proto_rawDesc)))
	})
	return file_proto_Voting_proto_rawDescData
}

var file_proto_Voting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_Voting_proto_goTypes = []any{
	(*Vote)(nil),     // 0: Vote
	(*NodeInfo)(nil), // 1: NodeInfo
}
var file_proto_Voting_proto_depIdxs = []int32{
	1, // 0: VotingService.StartVoting:input_type -> NodeInfo
	0, // 1: VotingService.StartVoting:output_type -> Vote
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_Voting_proto_init() }
func file_proto_Voting_proto_init() {
	if File_proto_Voting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_Voting_proto_rawDesc), len(file_proto_Voting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_Voting_proto_goTypes,
		DependencyIndexes: file_proto_Voting_proto_depIdxs,
		MessageInfos:      file_proto_Voting_proto_msgTypes,
	}.Build()
	File_proto_Voting_proto = out.File
	file_proto_Voting_proto_goTypes = nil
	file_proto_Voting_proto_depIdxs = nil
}
